name: Deploy to Google Cloud

on:
  push:
    branches:
      - main  # Déclencheur sur les push dans la branche main
  pull_request:
    branches:
      - main  # Déclencheur sur les pull requests pour la branche main

jobs:
  deploy:
    name: Deploy to GCP
    runs-on: ubuntu-latest  # Exécute ce job sur un runner Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Action pour récupérer le code du dépôt

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCLOUD_AUTH }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Deploy to GCP
        run: 
          gcloud auth login
          gcloud functions deploy function-hotel-list \
          --gen2 \
          --runtime=nodejs20 \
          --region=us-east1  \
          --source=. \
          --entry-point=getHotels \
          --trigger-http --allow-unauthenticated
