name: Deploy to Google Cloud

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Run this job on an Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Action to check out the repository code

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}  # Your Google Cloud project ID
          service_account_key: ${{ secrets.SVCAccount }}  # The secret service account key
          export_default_credentials: true

      - name: Deploy to GCP
        run: |
          gcloud beta functions deploy function-hotel-list --quiet --region=us-east1 --source=. --entry-point=getHotels --trigger-http --allow-unauthenticated --runtime=nodejs20
